server:
  port: 8081
shiro:
  client:
    clientId: c1ebe466-1cdc-4bd3-ab69-77c3561b9dee
    clientSecret: d8346ea2-6017-43ed-ad68-19c0f971738b
    accessTokenUrl: http://localhost:8080/oauth-server/accessToken
    redirectUrl: http://localhost:8080/index
    responseType: code
    authorizeUrl: http://localhost:8080/oauth-server/authorize